name: Build Multi-Platform

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Permite clicar no botão "Run" manualmente na aba Actions

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Se o Linux falhar, não cancela o Windows (e vice-versa)
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      # Baixa código
      - uses: actions/checkout@v4

      # Prepara Linux
      # Instala libpcap e python3-tk
      - name: Install Linux System Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev python3-tk

      # Prepara o Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      # Prepara o Rust
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # Instala bibliotecas Python (comum para os dois)
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin pyinstaller scapy requests

      - name: Build Rust Extension
        shell: bash
        working-directory: ./rust_src
        run: |
          maturin build --release
          pip install target/wheels/*.whl

      # Gera o Executável (Windows)
      # Usa ponto-e-vírgula (;) para separar assets
      - name: Build Exe (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller --noconsole --onefile --name "PyNetSketch" --icon="assets/app_icon.ico" --add-data "assets;assets" --hidden-import "pynetsketch_core" gui_app.py

      # 8. Gera o Executável (Linux)
      # Usa dois-pontos (:) para separar assets e não tem ícone .ico
      - name: Build Binary (Linux)
        if: runner.os == 'Linux'
        run: |
          pyinstaller --noconsole --onefile --name "PyNetSketch" --add-data "assets:assets" --hidden-import "pynetsketch_core" gui_app.py

      # 9. Faz o Upload do arquivo pronto para você baixar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyNetSketch-${{ matrix.os }}
          path: |
            dist/PyNetSketch.exe
            dist/PyNetSketch
